// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// generate_bxi
void generate_bxi(const std::string& bamFile);
RcppExport SEXP bxBam_generate_bxi(SEXP bamFileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bamFile(bamFileSEXP);
    generate_bxi(bamFile);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"bxBam_generate_bxi", (DL_FUNC) &bxBam_generate_bxi, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bxBam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
