// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// query_bam_index
DataFrame query_bam_index(CharacterVector bam_file_name, CharacterVector bam_index_path, CharacterVector index_name, CharacterVector key);
RcppExport SEXP _bambi_query_bam_index(SEXP bam_file_nameSEXP, SEXP bam_index_pathSEXP, SEXP index_nameSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type bam_file_name(bam_file_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bam_index_path(bam_index_pathSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type index_name(index_nameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(query_bam_index(bam_file_name, bam_index_path, index_name, key));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bambi_query_bam_index", (DL_FUNC) &_bambi_query_bam_index, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bambi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
