# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

query_bam_index <- function(bam_file_name, bam_index_path, index_name, key) {
    .Call('bambi_query_bam_index', PACKAGE = 'bambi', bam_file_name, bam_index_path, index_name, key)
}

