# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

query_bam_index <- function(bam_file_name, bam_index_path, key_type, key_value) {
    .Call(`_bambi_query_bam_index`, bam_file_name, bam_index_path, key_type, key_value)
}

rcpp_hello_world <- function() {
    .Call(`_bambi_rcpp_hello_world`)
}

