# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

barcodedReads <- function(bamFile, indexFile, barcode) {
    invisible(.Call('bxBam_barcodedReads', PACKAGE = 'bxBam', bamFile, indexFile, barcode))
}

generate_bxi <- function(bamFile) {
    invisible(.Call('bxBam_generate_bxi', PACKAGE = 'bxBam', bamFile))
}

